# Generated by Django 5.1.7 on 2025-04-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_alter_driver_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='file_upload',
            field=models.FileField(upload_to='driver/uploaded_files'),
        ),
    ]
